name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4.2.0
      with:
        dotnet-version: 9.0.x

    - name: Install WASM-Tools
      run: dotnet workload install wasm-tools

    - name: Install dependencies
      run: dotnet restore

    - name: Build win-x64
      run: dotnet publish SolisManager.sln -c Release --runtime win-x64 --self-contained -o ./publish-dir/SolisManager-win /p:AssemblyVersion=1.0.${{ github.run_number }}
      
    - name: Build linux-x64
      run: dotnet publish SolisManager.sln -c Release --runtime linux-x64 --self-contained -o ./publish-dir/SolisManager-linux /p:AssemblyVersion=1.0.${{ github.run_number }}
      
    - name: Build osx-x64
      run: dotnet publish SolisManager.sln -c Release --runtime osx-x64 --self-contained -o ./publish-dir/SolisManager-osx  /p:AssemblyVersion=1.0.${{ github.run_number }}
    
    - name: Zip the Win release
      run: zip -r ./artifacts/SolisManager-win.zip ./publish-dir/SolisManager-win/*.*

    - name: Zip the OSX release
      run: zip -r ./artifacts/SolisManager-osx.zip ./publish-dir/SolisManager-osx/*.*

    - name: Zip the Linux release
      run: zip -r ./artifacts/SolisManager-linux.zip ./publish-dir/SolisManager-linux/*.*

    - name: Create the Release
      id: create_release
      if: ${{ github.event_name == 'push' }}
      uses: actions/create-release@v1.1.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: 1.0.${{ github.run_number }}
        release_name: Release 1.0.${{ github.run_number }}
        draft: false
        
    - name: Upload SolisManager-win
      if: ${{ github.event_name == 'push' }}
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/SolisManager-win.zip
        asset_name: SolisManager-win.zip
        asset_content_type: application/exe

    - name: Upload SolisManager-linux
      if: ${{ github.event_name == 'push' }}
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/SolisManager-linux.zip
        asset_name: SolisManager-linux.zip
        asset_content_type: application/exe

    - name: Upload SolisManager-osx
      if: ${{ github.event_name == 'push' }}
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/SolisManager-osx.zip
        asset_name: SolisManager-osx.zip
        asset_content_type: application/exe