name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix: 
        target: [mac, linux, windows]
        include: 
          - target: windows
            os: ubuntu-latest
            runtime: win-x64
          - target: linux
            os: ubuntu-latest
            runtime: linux-x64
          - target: mac
            os: macos-latest
            runtime: osx-x64
     
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4.2.0
      with:
        dotnet-version: 9.0.x

    - name: Install WASM-Tools
      run: dotnet workload install wasm-tools

    - name: Build SolisManager-${{matrix.target}}
      run: dotnet publish SolisManager/SolisManager.csproj -c Release --runtime ${{matrix.runtime}} --self-contained true -p:PublishTrimmed=false --property:PublishDir=${{github.workspace}}/publish /p:Version=1.0.${{github.run_number}}
        
    - name: Zip the release
      run: |
           pushd ${{github.workspace}}/publish
           zip -r ${{github.workspace}}/publish/SolisManager-${{matrix.target}}.zip . 
           popd

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: ${{github.workspace}}/publish/SolisManager-${{matrix.target}}.zip
        name: Release 1.0.${{ github.run_number }}
        tag_name: 1.0.${{ github.run_number }}
        make_latest: true

